---
prompt_file: instructions/J/template_response_rec.json
eval_file: data_test/DuRecDial_ENGLISH_CRS_REC.json
dataset_name: DuRecDial_ENGLISH
with_guidance: True
guidance: REC
task: CRS
shot: 3
tag: test
temperature: 1.0
top_p: 0.95