---
prompt_file: instructions/template_response.json
eval_file: data_test/DuRecDial_ENGLISH_CRS.json
dataset_name: DuRecDial_ENGLISH
task: CRS
shot: 1
tag: test
model: LLAMA
temperature: 1.0
top_p: 0.95